[build]
  base = "med-connect-WebFront"
  publish = "med-connect-WebFront/dist/med-connect"
  command = "ng build --configuration production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
